### ISSUE TITLE
gunicorn se cierra por timeout

### ISSUE THREAD

**Issue by FranFunes** [FranFunes/PETfectior_Client#60]
- Aplicación iniciada, sin otras acciones de por medio.
- Navegador abierto en /tasks.
- Una única tarea en la base de datos.
- Los requests a /get_tasks_table se resuelven sin problemas, hasta que uno se demora y falla.
- En el log de la app se ve:
petfectior-client-dev  | [2024-09-13 16:32:27 -0300] [1] [CRITICAL] WORKER TIMEOUT (pid:153)                            
petfectior-client-dev  | [2024-09-13 16:32:27 -0300] [153] [ERROR] Error handling request (no URI read)                 
petfectior-client-dev  | Traceback (most recent call last):                                                             
petfectior-client-dev  |   File "/home/petfectior/envPETfectiorClient/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle                                                                                               
petfectior-client-dev  |     req = next(parser)                                                                         
petfectior-client-dev  |           ^^^^^^^^^^^^                                                                         
petfectior-client-dev  |   File "/home/petfectior/envPETfectiorClient/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__                                                                                               
petfectior-client-dev  |     self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)     
petfectior-client-dev  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     
petfectior-client-dev  |   File "/home/petfectior/envPETfectiorClient/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__                                                                                             
petfectior-client-dev  |     super().__init__(cfg, unreader, peer_addr)                                                 
petfectior-client-dev  |   File "/home/petfectior/envPETfectiorClient/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__                                                                                              
petfectior-client-dev  |     unused = self.parse(self.unreader)                                                         
petfectior-client-dev  |              ^^^^^^^^^^^^^^^^^^^^^^^^^                                                         
petfectior-client-dev  |   File "/home/petfectior/envPETfectiorClient/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse                                                                                                petfectior-client-dev  |     self.get_data(unreader, buf, stop=True)                                                    
petfectior-client-dev  |   File "/home/petfectior/envPETfectiorClient/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data                                                                                             petfectior-client-dev  |     data = unreader.read()                                                                     
petfectior-client-dev  |            ^^^^^^^^^^^^^^^                                                                     
petfectior-client-dev  |   File "/home/petfectior/envPETfectiorClient/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read                                                                                                 
petfectior-client-dev  |     d = self.chunk()                                                                           
petfectior-client-dev  |         ^^^^^^^^^^^^                                                                          
petfectior-client-dev  |   File "/home/petfectior/envPETfectiorClient/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk                                                                                                petfectior-client-dev  |     return self.sock.recv(self.mxchunk)                                                        
petfectior-client-dev  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                        
petfectior-client-dev  |   File "/home/petfectior/envPETfectiorClient/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort                                                                                         petfectior-client-dev  |     sys.exit(1)                                                                                
petfectior-client-dev  | SystemExit: 1                                                                                  
petfectior-client-dev  | [2024-09-13 16:32:28 -0300] [153] [INFO] Worker exiting (pid: 153)                             
petfectior-client-dev  | [2024-09-13 16:32:29 -0300] [1] [ERROR] Worker (pid:153) was sent SIGKILL! Perhaps out of memory?                                                                                                                      petfectior-client-dev  | [2024-09-13 16:32:29 -0300] [194] [INFO] Booting worker with pid: 194

**Comment by FranFunes** [comment]
El uso de cpu de la app es demasiado alto (entre 75% y 80%), incluso cuando no está haciendo nada. Probablemente se deba a algún while que no está limitado.

**Comment by FranFunes** [comment]
Deteniendo cada proceso por separado, encontré que el consumo de cpu está en el Task Manager, cuyo main loop se ejecuta continuamente si existe alguna tarea. Esto también podría estar relacionado con el issue #59, dado que Task Manager está leyendo continuamente la tabla Task, bloqueando la base de datos.

**Comment by FranFunes** [comment]
Añadiendo una pausa en el loop del TaskManager se soluciona parcialmente el uso de cpu elevado, pero el error de timeout en gunicorn sigue ocurriendo al consultar la tabla de tareas cuando esta tiene 150 filas o más.

**Comment by FranFunes** [comment]
Solucionado en el commit https://github.com/FranFunes/PETfectior_Client/commit/d2438dda2d02ab98a57bf53a81b2fa909c74539e
